# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: '2010-09-09'
Description: Create role allowing the drs_plan_automation AWS lambda function to assume this role and perform DRS job operations, SSM execution for PreWave / PostWave, etc in the account.
Parameters:
  SourceAccountNumber:
    Description: The AWS Account ID where the DRS Plan Automation solution is deployed and drs_plan_automation AWS Lambda function is running.
    Type: String

Resources:
  EC2ToDRSTagReplicatorAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:  "drs_plan_automation_account_role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref SourceAccountNumber
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      Policies:
        - PolicyName: PerformDRSPlanAutomationOperations
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: PublishPlanAutomationUpdates
                Effect: Allow
                Action:
                  - sns:Publish
                Resource: "*"
              - Sid: ExecuteDRSOperations
                Effect: Allow
                Action:
                  - drs:DescribeJobs
                  - drs:DescribeJobLogItems
                  - drs:DescribeSourceServers
                  - drs:StartRecovery
                Resource: "*"
              - Sid: ExecuteSSMActions
                Effect: Allow
                Action:
                  - ssm:DescribeAutomationExecutions
                  - ssm:StartAutomationExecutions
                Resource: "*"


