AWSTemplateFormatVersion: '2010-09-09'
Description: "WAF for CloudFront Distribution, enable ip filtering..."
Parameters:
  # Customer Specific Tags - Example
  AllowedCIDRs:
    Description: Allowed Public CIDRs to DRS interface comma separated list (e.g. "192.0.2.44/32", "192.0.2.0/24", "192.0.0.0/16")
    Type: String
Resources:
#  drswaf:
#    Type: AWS::WAFv2::WebACL
#    Properties:
#      DefaultAction:
#        Block: { }
#      Description: WAF for DRS Plan Automation
#      Rules:
#        - Action:
#            Allow: { }
#          Name: webacl-allowed-ips
#          Priority: 0
#          Statement:
#            IPSetReferenceStatement:
#              Arn: !GetAtt drsallowedips.Arn
#          VisibilityConfig:
#            CloudWatchMetricsEnabled: False
#            MetricName: webacl-allowed-ips
#            SampledRequestsEnabled: False
#      VisibilityConfig:
#        CloudWatchMetricsEnabled: False
#        MetricName: webacl
#        SampledRequestsEnabled: False
#      Scope: CLOUDFRONT

  drswaf:
    Type: AWS::WAF::WebACL
    Properties:
      DefaultAction:
        Type: ALLOW
      Name: WAF for DRS Plan Automation
      Rules:
        - Action:
            Type: ALLOW
          RuleId: !Ref drsallowedipsrule
          Priority: 0
      MetricName: webacl

  drsallowedipsrule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: drsallowedips
      Name: drsallowedips
      Predicates:
        - DataId:  !Ref drsallowedips
          Negated: false
          Type: IPMatch

  drsallowedips:
    Type: AWS::WAF::IPSet
    Properties:
      Name: Allowed CIDRs for DRS Plan Automation frontend web interface
      IPSetDescriptors:
        - Type: IPV4
          Value: !Ref AllowedCIDRs

#  drsallowedips:
#    Type: AWS::WAFv2::IPSet
#    Properties:
#      Addresses:
#        - Ref: AllowedCIDRs
#      Description: Allowed CIDRs for DRS Plan Automation frontend web interface
#      IPAddressVersion: IPV4
#      Scope: CLOUDFRONT


#      Tags:
#        - Tag


Outputs:
  drswafarn:
    Value: !Ref drswaf
    Description: "WAF for DRS CloudFront Distribution"
    Export:
      Name: "drs-plan-automation-waf"

